credentials:
  usernames:
    admin:
      name: Administrador
      password: $2b$12$Pb0ZxrCHNTPQoLsdBR1UGe6O.3n7ECVIcqiPXHH7qn.zpb2NnLoGK  # admin123
      role: admin
    user:
      name: Usuario Regular
      password: $2b$12$lQOXx1.mfQz5GD9DJM.8SeWP1tCJ.2F/hPrtrrm85w7e6ATUlwglu  # user123
      role: user
cookie:
  expiry_days: 30
  key: flota_vehicular_app
  name: flota_cookie
